---
codenotary:
    signer: "red.avtovo@gmail.com"

build_from:
    amd64: "ghcr.io/home-assistant/base-debian:trixie"
    aarch64: "ghcr.io/home-assistant/base-debian:trixie"

args:
    HEV_VERSION: "2.10.1"
