#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -euo pipefail

bashio::log.info "Starting Copyparty..."

USERNAME=$(bashio::config 'username')
PASSWORD=$(bashio::config 'password')
ANON=$(bashio::config 'anonymous_access')
INDEXING=$(bashio::config 'enable_indexing')
SERVER_NAME=$(bashio::config 'server_name')

if ! bashio::var.has_value "${PASSWORD}" || [ "${PASSWORD}" = "changeme" ]; then
    bashio::log.warning "Using default/empty password — change it before exposing Copyparty"
fi

mkdir -p /cfg /cfg/hists /config /addon_configs /share /media /homeassistant

CFG_FILE=/cfg/copyparty.conf

ANON_LINE=""
case "${ANON}" in
    read)
        ANON_LINE="    r: *"
        ;;
    readwrite)
        ANON_LINE="    rw: *"
        ;;
esac

INDEX_FLAGS=""
if bashio::var.true "${INDEXING}"; then
    INDEX_FLAGS=$'  e2dsa\n  e2ts'
fi

USERNAME="${USERNAME//$'\n'/}"
PASSWORD="${PASSWORD//$'\n'/}"

write_volume() {
    local url_path="$1"
    local fs_path="$2"
    local perms="$3"

    {
        echo "[${url_path}]"
        echo "  ${fs_path}"
        echo "  accs:"
        echo "    ${perms}: ${USERNAME}"
        if [ -n "${ANON_LINE}" ]; then
            # ssl volume stays authenticated-read even if anon is readwrite
            if [ "${fs_path}" = "/ssl" ]; then
                :
            else
                echo "${ANON_LINE}"
            fi
        fi
        echo
    } >> "${CFG_FILE}"
}

cat > "${CFG_FILE}" << EOF
# Generated by Home Assistant Copyparty app — overwritten on restart.
# Drop extra *.conf files in /config for advanced settings (merged at startup).

[global]
  p: 3923
  ansi
  hist: /cfg/hists/
  name: ${SERVER_NAME}
${INDEX_FLAGS}

[accounts]
  ${USERNAME}: ${PASSWORD}

EOF

write_volume "/share" "/share" "rwmda"
write_volume "/media" "/media" "rwmda"
write_volume "/addon-config" "/config" "rwmda"
write_volume "/addon-configs" "/addon_configs" "rwmda"
write_volume "/homeassistant" "/homeassistant" "rwmda"
write_volume "/ssl" "/ssl" "r"

EXTRA_ARGS=()
shopt -s nullglob
for f in /config/*.conf; do
    bashio::log.info "Loading extra config: ${f}"
    EXTRA_ARGS+=(-c "${f}")
done
shopt -u nullglob

bashio::log.info "Volumes: /share /media /config /addon_configs /homeassistant (rw admin) and /ssl (ro)"
bashio::log.info "Listening on :3923"

exec python3 -m copyparty -c "${CFG_FILE}" "${EXTRA_ARGS[@]}"
